default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || 10 %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: practical_examples_development

test:
  <<: *default
  database: practical_examples_test

production:
  <<: *default
  database: practical_examples_production
